CREATE USER rauf IDENTIFIED BY "12345";

GRANT CREATE SESSION TO rauf;

GRANT UNLIMITED TABLESPACE TO rauf;

ALTER USER rauf QUOTA UNLIMITED ON USERS;

GRANT CREATE TABLE TO rauf;

CONNECT rauf/12345;

GRANT SELECT,INSERT,UPDATE,DELETE ON TEACHERS TO rauf;

GRANT ALL ON TEACHERS TO rauf;


CREATE TABLE TEACHER(
Id NUMBER PRIMARY KEY,
Name NVARCHAR2(30),
Surname NVARCHAR2(50),
AGE DATE
)

INSERT INTO TEACHER (Id,Name,Surname)
VALUES(1,'Rauf','Ehmedli');
INSERT INTO TEACHER (Id,Name,Surname)
VALUES(2,'Enver','Zeynalli');
INSERT INTO TEACHER (Id,Name,Surname)
VALUES(3,'Seymur','Hesenli');

ALTER TABLE TEACHER RENAME TO TEACHERS;

ALTER TABLE TEACHERS RENAME COLUMN age to salary;

ALTER TABLE TEACHERS ADD FENN NVARCHAR2(30);

ALTER TABLE TEACHERS MODIFY salary NVARCHAR2(20);

ALTER TABLE TEACHERS DROP COLUMN salary;

DROP TABLE TEACHERS

FLASHBACK TABLE TEACHERS TO BEFORE DROP;

SELECT * FROM TEACHERS
