SELECT VALUE FROM V$NLS_PARAMETERS WHERE PARAMETER='NLS_DATE_FORMAT';

SELECT SYSDATE FROM DUAL;

ALTER SESSION SET NLS_DATE_FORMAT = 'DD-MM-YYYY';
--TO_CHAR
SELECT TO_CHAR(SYSDATE,'DD-MON-YY HH24:MM:SS') AS TARIX FROM DUAL;

SELECT TO_CHAR(SYSDATE,'YYYY/MM/DD') AS TARIX FROM DUAL;

SELECT TO_CHAR(SYSDATE,'Month DD-YY') AS TARIX FROM DUAL;

SELECT TO_CHAR(SYSDATE,'FMMonth DD-YY') AS TARIX FROM DUAL;

SELECT TO_CHAR(SYSDATE,'FMMon DDTH-YYYY') AS TARIX FROM DUAL;

--TO_DATE

SELECT TO_DATE('09/03/2023', 'DD/MM/YYYY') AS TARIX FROM DUAL;

SELECT TO_DATE('090323', 'DDMMYY') AS TARIX FROM DUAL;