SELECT LTRIM('12345SALAM','12345') FROM DUAL;

SELECT LTRIM('    SALAM') FROM DUAL;

SELECT LTRIM('----SALAM','-') FROM DUAL;

SELECT LTRIM('$$SALAM-$$-123','$') FROM DUAL;

SELECT LTRIM('ABCSALAMABC','ABC') FROM DUAL;

SELECT RTRIM('SALAM12345','12345') FROM DUAL;

SELECT RTRIM('SALAM    ') FROM DUAL;

SELECT RTRIM('SALAM---','-') FROM DUAL;

SELECT RTRIM('$$SALAM$-12$$$','$') FROM DUAL;

SELECT RTRIM('ABCSALAMABC','ABC') FROM DUAL;

SELECT RTRIM('132$$$SALAM-132$$$','132$') FROM DUAL;

select
decode(currency_id,
11, 'AZN',
12, 'Turk liresi',
13, 'USD',
14, 'Rubl',
'diger pul vahididir')
as pul_vahidi, l.* from loan l;

SELECT NVL(NULL,250) FROM DUAL;

SELECT NVL(100,NULL) FROM DUAL;

SELECT NVL2(100,'NULL DEYIL','NULLDUR') FROM DUAL;

SELECT nullif(100,200) FROM DUAL;

SELECT nullif(100,100) FROM DUAL;

SELECT nullif(CURRENCY_ID,12) FROM LOAN;

SELECT COALESCE(NULL,NULL,NULL) FROM DUAL;

SELECT COALESCE(238,NULL,9822) FROM DUAL;

SELECT COALESCE(5,4,6) FROM DUAL;










