CREATE TABLE FILIAL(
filial_id NUMBER PRIMARY KEY,
filial_name NVARCHAR2(15) NOT NULL UNIQUE
);

CREATE TABLE isciler(
id NUMBER CONSTRAINT id_p PRIMARY KEY,
name VARCHAR2(30) CONSTRAINT na_n NOT NULL,
surname VARCHAR2(30) CONSTRAINT su_n NOT NULL,
salary NVARCHAR2(15) CONSTRAINT sa_n NOT NULL,
Card_number NUMBER(15) CONSTRAINT c_n NOT NULL UNIQUE,
Filial_id NUMBER ,
vezife NVARCHAR2(10) CONSTRAINT ve_n NOT NULL,
CONSTRAINT f_fk FOREIGN KEY (Filial_id) REFERENCES FILIAL(filial_id)
);



INSERT INTO FILIAL VALUES(1, 'N.Nerimanov');
INSERT INTO FILIAL VALUES(2, '28 May');
INSERT INTO FILIAL VALUES(3, 'Nizami');

INSERT INTO isciler VALUES(1,'Rauf','Ahmedov', 1530, 145896587423516, 1, 'Back-end');
INSERT INTO isciler VALUES(2,'Eyvaz','Suleymanov', 1569, 145896584125986, 3,  'Front-end');
INSERT INTO isciler VALUES(3,'Huseyn','Cafarli', 1460, 145896587421647, 2, 'sql dev');

select * from isciler;
select * from filial;

select i.id, i.name, i.surname, f.filial_name, i.vezife FROM isciler i 
INNER JOIN filial f on i.filial_id = f.filial_id;

DROP TABLE filial;

SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'ISCILER';

ALTER TABLE isciler DROP CONSTRAINT F_FK;

DROP TABLE ISCILER;

CREATE TABLE isciler(
id NUMBER CONSTRAINT id_p PRIMARY KEY,
name VARCHAR2(30) CONSTRAINT na_n NOT NULL,
surname VARCHAR2(30) CONSTRAINT su_n NOT NULL,
salary NVARCHAR2(15) CONSTRAINT sa_n NOT NULL,
Card_number NUMBER(15) CONSTRAINT c_n NOT NULL UNIQUE,
Filial_id NUMBER ,
vezife NVARCHAR2(10) CONSTRAINT ve_n NOT NULL,
CONSTRAINT f_fk FOREIGN KEY (Filial_id) REFERENCES FILIAL(filial_id) ON DELETE SET NULL
);

DELETE FROM filial WHERE filial_id=1;

DROP TABLE ISCILER;

CREATE TABLE isciler(
id NUMBER CONSTRAINT id_p PRIMARY KEY,
name VARCHAR2(30) CONSTRAINT na_n NOT NULL,
surname VARCHAR2(30) CONSTRAINT su_n NOT NULL,
salary NVARCHAR2(15) CONSTRAINT sa_n NOT NULL,
Card_number NUMBER(15) CONSTRAINT c_n NOT NULL UNIQUE,
Filial_id NUMBER ,
vezife NVARCHAR2(10) CONSTRAINT ve_n NOT NULL,
CONSTRAINT f_fk FOREIGN KEY (Filial_id) REFERENCES FILIAL(filial_id) ON DELETE CASCADE
);

DELETE FROM filial WHERE filial_id=1;

ALTER TABLE ISCILER MODIFY vezife INVISIBLE;

ALTER TABLE ISCILER MODIFY vezife VISIBLE;