--Loan partition


alter table sys.loan modify
partition by range (act_date) (
PARTITION pr1 VALUES LESS THAN (TO_DATE('01-01-2005', 'DD-MM-YYYY')),
PARTITION pr2 VALUES LESS THAN (TO_DATE('01-01-2010', 'DD-MM-YYYY')),
PARTITION pr3 VALUES LESS THAN (TO_DATE('01-01-2015', 'DD-MM-YYYY')),
PARTITION pr4 VALUES LESS THAN (TO_DATE('01-01-2020', 'DD-MM-YYYY')),
PARTITION pr5 VALUES LESS THAN (MAXVALUE)
);

